version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vexacore_mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vexacore_network

  redis:
    image: redis:7-alpine
    container_name: vexacore_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vexacore_network

  app:
    build: .
    container_name: vexacore_ai
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - vexacore_network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  vexacore_network:
    driver: bridge 